networks:
  app_network:
    external: true

volumes:
  paperless-ai_data:
    external: true
    name: paperless-ai_paperless-ai_data

services:
  paperless-ai:
    image: clusterzx/paperless-ai:latest@sha256:2b65888163fd59716f1c8285b31c5bd0b30c9c3c192c42b516688e3887d4ba60
    container_name: paperless-ai
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - paperless-ai_data:/app/data
