networks:
  app_network:
    external: true

volumes:
  signal-cli-config:
    name: signal-cli-config

services:
  signal-cli:
    image: registry.gitlab.com/packaging/signal-cli/signal-cli-jre:latest
    command: daemon --http 0.0.0.0:7583
    restart: unless-stopped
    ports:
      - "127.0.0.1:17583:7583"
    volumes:
      - signal-cli-config:/var/lib/signal-cli
    tmpfs:
      - "/tmp:exec"
    networks:
      - app_network
