services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/udp"
      - "8080:80/tcp" # host 8080 -> container 80
      - "8443:443/tcp" # host 8443 -> container 443
      - "8443:443/udp" # QUIC on 443 if enabled
      - "3100:3000/tcp" # setup UI moved off 3001 (in use)
      - "853:853/tcp"
      - "784:784/udp"
      - "853:853/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
    volumes:
      - /srv/data/projects/docker/adguard/work:/opt/adguardhome/work
      - /srv/data/projects/docker/adguard/conf:/opt/adguardhome/conf
