networks:
  cloudflared:
    external: true
  app_network:
    external: true

services:
  music-assistant-alexa-api:
    build: .
    container_name: music-assistant-alexa-api
    image: ghcr.io/alams154/music-assistant-alexa-api:latest
    restart: unless-stopped
    ports:
      - 3300:3000
    networks:
      - cloudflared
      - app_network
