services:
  cloudflared:
    image: cloudflare/cloudflared@sha256:e9bcb2ef08d25632ff74344e73a025f4f4bf12718335b196fa0e670cacace8c5
    container_name: cloudflared
    environment:
      - TZ=America/Vancouver
      - TUNNEL_TOKEN=${API_TOKEN}
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    networks:
      - cloudflared

networks:
  cloudflared:
    name: cloudflared
