networks:
  app_network:
    external: true

services:
  litellm:
    image: ghcr.io/berriai/litellm:v1.81.9-stable@sha256:1ecd7561f7e0349fbf5ab3355e0258dd724395ec18ffc91297c5d958f866855c
    restart: unless-stopped
    volumes:
      - /srv/data/projects/infra/services/litellm/config.yaml:/app/config.yaml:ro
    command: ["--config", "/app/config.yaml", "--port", "4000"]
    ports:
      - "4000:4000"
    environment:
      STORE_MODEL_IN_DB: "True"
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      LITELLM_SALT_KEY: ${LITELLM_SALT_KEY}
      LITELLM_LOG: ${LITELLM_LOG}
      #LITELLM_LOG="DEBUG"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      SAMBANOVA_API_KEY: ${SAMBANOVA_API_KEY}
      PERPLEXITYAI_API_KEY: ${PERPLEXITYAI_API_KEY}
      #NO_DOCS="True"
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      DATABASE_URL: ${DATABASE_URL}
      LOCAL_API_BASE: ${LOCAL_API_BASE}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:4000/health/liveliness || exit 1",
        ]
      interval: 30s # Perform health check every 30 seconds
      timeout: 10s # Health check command times out after 10 seconds
      retries: 3 # Retry up to 3 times if health check fails
      start_period: 40s # Wait 40 seconds after container start before beginning health checks
    networks:
      - app_network
