networks:
  cloudflared:
    external: true
  app_network:
    external: true

volumes:
  model-cache:
    external: true
    name: immich_model-cache

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v2.5.6@sha256:aa163d2e1cc2b16a9515dd1fef901e6f5231befad7024f093d7be1f2da14341a
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - UPLOAD_LOCATION=${UPLOAD_LOCATION}
      - DB_DATA_LOCATION=${DB_DATA_LOCATION}
      - THUMB_LOCATION=${THUMB_LOCATION}
      - TZ=${TZ}
      - IMMICH_VERSION=${IMMICH_VERSION}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
    ports:
      - "2283:2283"
    depends_on:
      - redis_imm
      - database_imm
    restart: always
    healthcheck:
      disable: false
    networks:
      - cloudflared
      - app_network

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:v2.5.6@sha256:b213fa3c82d27a21a299c46ffbb38a091f18384db1ad67d409a3b34fe0fce556
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    environment:
      - UPLOAD_LOCATION=${UPLOAD_LOCATION}
      - DB_DATA_LOCATION=${DB_DATA_LOCATION}
      - THUMB_LOCATION=${THUMB_LOCATION}
      - TZ=${TZ}
      - IMMICH_VERSION=${IMMICH_VERSION}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
    restart: always
    healthcheck:
      disable: false
    networks:
      - app_network

  redis_imm:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - app_network

  database_imm:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
      DB_STORAGE_TYPE: "HDD"
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 256mb
    restart: always
    networks:
      - app_network
