volumes:
  music-assistant-server-data:
    external: true
    name: home-assistant_music-assistant-server-data
  homeassistant-data:
    external: true
    name: home-assistant_homeassistant-data

networks:
  homeassistant:
    name: homeassistant
  cloudflared:
    external: true
  app_network:
    external: true

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:2026.2.0@sha256:043ab74ba0ad529734d7d77ca3e893f286410864619329d5e8ca0524c3d260c1"
    volumes:
      - homeassistant-data:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    environment:
      - TZ=America/Vancouver
        # not used when network mode is host ports:
        #- 8095:8095
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

  music-assistant-server:
    #image: ghcr.io/music-assistant/server:latest
    image: ghcr.io/music-assistant/server:beta@sha256:72f6e2fc2a98721c657806caa55905d2e32df6d889c7a9364bfef1b62087a16d
    container_name: music-assistant-server
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    volumes:
      - music-assistant-server-data:/data/
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      - LOG_LEVEL=info
