volumes:
  music-assistant-server-data:
    external: true
    name: home-assistant_music-assistant-server-data
  homeassistant-data:
    external: true
    name: home-assistant_homeassistant-data

networks:
  homeassistant:
    name: homeassistant
  cloudflared:
    external: true
  app_network:
    external: true

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:2026.2.2@sha256:3e2dff545c46e91f4ab2b21597016011d76d0de58bc8eaf51d75e841f337bf88"
    volumes:
      - homeassistant-data:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    environment:
      - TZ=America/Vancouver
        # not used when network mode is host ports:
        #- 8095:8095
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

  music-assistant-server:
    #image: ghcr.io/music-assistant/server:latest
    image: ghcr.io/music-assistant/server:beta@sha256:06b69a80fc1c1c3cd7ca8dc81a65d7487f725e8c1627517544b89849789dbafc
    container_name: music-assistant-server
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    volumes:
      - music-assistant-server-data:/data/
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      - LOG_LEVEL=info
