networks:
  app_network:
    external: true

volumes:
  mosquito-data:
    external: true
    name: mosquitto_mosquito-data

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9011:9001
    volumes:
      - mosquito-data:/mosquitto
      - mosquito-data:/mosquitto/data
      - mosquito-data:/mosquitto/log
    networks:
      - app_network
