networks:
  app_network:
    external: true

volumes:
  mosquito-data:
    external: true
    name: mosquitto_mosquito-data

services:
  mosquitto:
    image: eclipse-mosquitto:2.1.2-alpine@sha256:9cfdd46ad59f3e3e5f592f6baf57ab23e1ad00605509d0f5c1e9b179c5314d87
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9011:9001
    volumes:
      - mosquito-data:/mosquitto
      - mosquito-data:/mosquitto/data
      - mosquito-data:/mosquitto/log
    networks:
      - app_network
