networks:
  app_network:
    external: true

volumes:
  signal-cli-config:
    name: signal-cli-rest

services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:0.97@sha256:5fcb8e8620f20f944d747627841ca97f19104acb3e1adb1d5c8983b5db422529
    restart: unless-stopped
    environment:
      MODE: json-rpc # supported: json-rpc, native, normal
    ports:
      - "7583:8080"
    volumes:
      - signal-cli-config:/home/.local/share/signal-cli
    networks:
      - app_network
