services:
  govee2mqtt:
    image: ghcr.io/wez/govee2mqtt:latest
    container_name: govee2mqtt
    restart: unless-stopped
    network_mode: host
    environment:
      GOVEE_EMAIL: ${GOVEE_EMAIL}
      GOVEE_PASSWORD: ${GOVEE_PASSWORD}
      GOVEE_API_KEY: ${GOVEE_API_KEY}
      GOVEE_MQTT_HOST: 127.0.0.1
      GOVEE_MQTT_PORT: 1883
      GOVEE_MQTT_USER: ${GOVEE_MQTT_USER}
      GOVEE_MQTT_PASSWORD: ${GOVEE_MQTT_PASSWORD}
      GOVEE_TEMPERATURE_SCALE: C
      RUST_LOG_STYLE: always
      TZ: America/Vancouver
