volumes:
  matter-data:

networks:
  homeassistant:
    name: homeassistant
    external: true

services:
  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable@sha256:170aa093ce91c76cde4cc390918307590f0f5558fcec93f913af3cb019e6562a
    container_name: matter-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - matter-data:/data

