networks:
  app_network:
    external: true

volumes:
  nginxproxymanager-data:
    external: true
    name: nginxproxymanager_nginxproxymanager-data

services:
  app:
    image: "jc21/nginx-proxy-manager:latest@sha256:cd9eba29ca132cb006729f2cb2660126453f84818c2f7d75963ad7b61ef696bd"
    restart: unless-stopped
    ports:
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
    volumes:
      - nginxproxymanager-data:/data
      - nginxproxymanager-data:/etc/letsencrypt
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
